Accretion/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('homepage.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from . import views

app_name = 'accounts'

urlpatterns = [
    path('home/', views.home),
    path('login/', login, {'template_name': 'accounts/login.html'}, name='login'),
    path('logout/', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/password/', views.change_password, name='change_password'),
    path('reset-password', password_reset, {'post_reset_redirect': 'accounts:password_reset_done',
                                            'email_template_name':'accounts/reset_password_email.html'},
         name='password-reset'),
    path('reset-password/done', password_reset_done, name='password_reset_done'),
    path('reset-password/confirm(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/', password_reset_confirm,
         {'post_reset_redirect': 'accounts:password_reset_complete'},
         name='password_reset_confirm'),
    path('reset-password/complete', password_reset_complete, name='password_reset_complete'),
]

# USE THIS FOR EMAIL SERVER CHANGE THIS WHILE DEPLOYMENT python -m smtpd -n -c DebuggingServer localhost:1025

homepage/urls.py
from django.urls import path, include
from homepage.views import HomeView

urlpatterns = [
    path('', HomeView.as_view()),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=70)
    country = models.CharField(max_length=70)
    phone = models.IntegerField(max_length=10, default=0)


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)

homepage/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    post = models.CharField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required = True)
    first_name = forms.CharField(required = True)
    last_name = forms.CharField(required = True)
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit = False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user

class Editprofile(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',
        )

homepage/forms.py
from django import forms
from homepage.models import Post

class HomeForm(forms.ModelForm):
    post = forms.CharField()

    class Meta:
        model = Post
        fields = ('post',)

Accretion/views.py
from django.shortcuts import redirect

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from accounts.forms import RegistrationForm, Editprofile
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
# Create your views here.


def register(request):
     if request.user.is_authenticated:
         return redirect('/home/')
     else:
         if request.method == 'POST':
             form = RegistrationForm(request.POST)
             if form.is_valid():
                 form.save()
                 return redirect('/home/')
             else:
                 return redirect('/accounts/register/')
         else:
             form = RegistrationForm()
             args = {'form': form}
             return render(request, 'accounts/reg_form.html', args)


def home(request):
    if request.user.is_authenticated:
        return redirect('/home/')
    else:
        return redirect('/accounts/login/')


def view_profile(request):
    args = {'user':request.user}
    return render(request, 'accounts/profile.html', args)


def edit_profile(request):
    if request.method == 'POST':
        form = Editprofile(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('/accounts/profile/')
    else:
        form = Editprofile(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/accounts/profile/')
        else:
            return redirect('/accounts/profile/password')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_password.html', args)

homepage/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect

from homepage.forms import HomeForm
from homepage.models import Post

class HomeView(TemplateView):
	template_name = 'homepage/home.html'

	def get(self, request):
		form = HomeForm()
		posts = Post.objects.all().order_by('-created')
		
		args = {'form': form, 'posts': posts}
		return render(request, self.template_name, args)

	def post(self, request):
		form = HomeForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.user = request.user
			post.save()
			text = form.cleaned_data['post']
			form = HomeForm()
			return redirect('/home/')
			
		args = {'form': form, 'text': text}	
		return render(request, self.template_name, args)

accounts/templates/accounts/edit_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Password</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit Changes</button>
    </form>
</body>
</html>

accounts/templates/accounts/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit your Profile</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit Changes</button>
    </form>
</body>
</html>

accounts/templates/accounts/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    Welcome Home {{user.get_username}}<br>
    <br>
    <br>
    To logout press the below button
    <a href="/accounts/logout/">
    <button>Logout</button></a>
</body>
</html>

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        input{
            outline: none;
	        border: none;

            font-family: Poppins-Regular;
            font-size: 16px;
            color: #fff;
            line-height: 1.2;

            display: block;
            width: 100%;
            height: 45px;
            background: transparent;
            padding: 0 5px 0 38px;
        }
    </style>
	<link rel="icon" type="image/png" href="favicon.ico"/>
	<link rel="stylesheet" type="text/css" href="/static/accounts/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="/static/accounts/fonts/iconic/css/material-design-iconic-font.min.css">
	<link rel="stylesheet" type="text/css" href="/static/accounts/css/main.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" method="post">
                    {% csrf_token %}
					<span class="login100-form-logo">
						<i class="glyphicon glyphicon-user"></i>
					</span>


					<span class="login100-form-title p-b-34 p-t-27">
						Log in
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Enter username">
                        {{ form.username }}
						<span class="focus-input100" data-placeholder="&#xf207;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
                        {{ form.password }}
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>

					<div class="contact100-form-checkbox">
						<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
						<label class="label-checkbox100" for="ckb1">
							Remember me
						</label>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

</body>
</html>

accounts/templates/accounts/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
    <h1>
        Logout successful.
    </h1>
</body>
</html>

accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profle of {{ user }}</title>
</head>
<body>
    <div>
        <h2>
            Profile:
        </h2>
        <p>
            <ul>
                <li>Username : {{ user }}</li>
                <li>Firstname : {{ user.first_name }}</li>
                <li>Lastname : {{ user.last_name }}</li>
                <li>Email : {{ user.email }}</li>
            </ul>
        </p>
    </div>
</body>
</html>

accounts/templates/accounts/reg_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register to Accretion</title>
</head>
<body>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Register</button>
        </form>
    </div>
</body>
</html>

accounts/templates/accounts/reset_password_email.html
	{% load i18n %}{% autoescape off %}
	{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

	{% trans "Please go to the following page and choose a new password:" %}
	{% block reset_link %}
	{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
	{% endblock %}
	{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

	{% trans "Thanks for using our site!" %}

	{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

	{% endautoescape %}

homepage/templates/homepage/home.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Home</title>
</head>
<body>
    <h1>Homepage</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <h2>{{ text }}</h2>
    {% for post in posts %}
        <h1>{{ post.post }}</h1>
        <p>Posted by {{ post.user.get_full_name }} on {{ post.created }}</p>
    {% endfor %}
</body>
</html>

homepage/templates/homepage/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Accretion</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfw23F8CExi1KgxUyJq13dy" crossorigin="anonymous">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<style type="text/css">
		body{
			padding: 0px;
			margin: 0px;
		}
		.edit{
			font-family: "Comic Sans MS", "Comic Sans";
			color: white;
		}
	</style>
</head>
<body>
  	<nav class="navbar navbar-default navbar-fixed-top" style="background-color: #23F8CE; padding-top: 0px;">
 		<span>
 			<span>
 		<div class="container">
 			<div class="container">
  				<h1 class="edit">Accretion</h1>
 			</span>
 		</span>
         <span>
             <span>
                 <a href="/accounts/register/"><h1 class="edit">Register</h1></a>
             </span>
         </span>
 			</div>
 		</div>
  	</nav>
  </body>
</html>